### ISSUE TITLE
Add command line parameters

### ISSUE THREAD

**Issue by timkolloch** [timkolloch/tandoor_importer#8]
Support command line parameters to control the program behavior from the command line.

## List of command line parameters to implement
- --override/-o override existing properties
- --log-level/-l: set the log level to trace, debug, info, warn or error
- --interactive/-i: Enable the interactive mode

**Comment by TheMBeat** [comment]
One option could be : 
--override -o : Override existing properties

**Comment by timkolloch** [comment]
> One option could be : 
> --override -o : Override existing properties

Yes, that is a good idea!
